controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

api_comparison:
    path:       /api/comparison
    controller: App\Controller\ComparisonController::comparison
    methods:    POST
